### ISSUE TITLE
Модели БД

### ISSUE THREAD

**Issue by BaronFAS** [Studio-Yandex-Practicum/predannoeserdce_bot_misha#3]
Предварительно модели:

- Хранение текстов ответов бота
- Хранение email
- Пользователи

Перед разработкой накидать схему для Read.me https://lucid.app/lucidchart/51f93cb7-9379-4588-be1b-61ddf4d9d637/view?page=0_0#

**Comment by Rolicat** [comment]
Предварительная схема https://lucid.app/lucidchart/6a9738cc-f0ec-4f6c-9166-2c06c187da82/edit?viewport_loc=-1225%2C-289%2C1365%2C733%2C0_0&invitationId=inv_ec421399-6757-4d53-97ee-53e31f9a130c
